apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
    - port: 13000
      targetPort: 12000
  webhook:
    my-webhook:
      port: "12000"
      endpoint: /push
      method: "POST"
